import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito_Sans, Poetsen_One } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const nunito = Nunito_Sans({ subsets: ['latin'], variable: '--font-nunito' });
const poetsen = Poetsen_One({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-poetsen',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${nunito.variable} ${poetsen.variable} antialiased  bg-[#fcf8f7] relative`}
      >
        {children}
      </body>
    </html>
  );
}
