import type { Metadata } from "next";
import { Nunito_Sans, Poetsen_One } from "next/font/google";

import "./globals.css";
import TanstackProvider from "@/providers/tanstack-provider";
import StoreProvider from "@/store/store-provider";

const nunito = Nunito_Sans({ subsets: ['latin'], variable: '--font-nunito' });
const poetsen = Poetsen_One({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-poetsen',
});

export const metadata: Metadata = {
  title: "Journey Rover",
  description: "Generated by me",
  icons: {
    icon:  { url: '/logo.ico', type: 'image/x-icon' },
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${nunito.variable} ${poetsen.variable} antialiased  bg-[#fcf8f7] relative`}
      >
        <TanstackProvider>
          <StoreProvider>
            {children}
          </StoreProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
